"""create nuevas tablas usuarios cotizaciones ordenes_compra

Revision ID: 78a26b97bf1e
Revises: 
Create Date: 2025-06-26 10:23:52.548760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78a26b97bf1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id_cotizacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('igv', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('flete', sa.Float(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('referencia', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cotizacion')
    )
    op.create_index(op.f('ix_cotizaciones_id_cotizacion'), 'cotizaciones', ['id_cotizacion'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_compra_id_orden'), 'ordenes_compra', ['id_orden'], unique=False)
    op.alter_column('usuarios', 'celular',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('usuarios', 'estado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('usuarios', 'fecha_modificacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.alter_column('usuarios', 'fecha_modificacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('usuarios', 'estado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('usuarios', 'celular',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.create_table('utilidad_venta',
    sa.Column('id_utilidad_venta', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_utilidad_venta'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario_roles',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['tipo_roles.id_roles'], name='FKme6m3sw9vo6513q4f7b5jkcog'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKor5vdfg7bv12b37vaawa9lee2'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_marca',
    sa.Column('id_log_marca', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tipo_acción', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='FKgrrnwmwn7xxx0kpcb78k4lqtf'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKhwuar6w4p641qrxl1j69n34hc'),
    sa.PrimaryKeyConstraint('id_log_marca'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categoria',
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_categoria_nombre', 'categoria', ['nombre'], unique=False)
    op.create_index('ft_nombre_categoria', 'categoria', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('UK35t4wyxqrevf09uwx9e9p6o75', 'categoria', ['nombre'], unique=True)
    op.create_table('producto_descuento_admin',
    sa.Column('id_producto_descuento_admin', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('descuento_admin', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('fecha_aplicacion', sa.DATE(), nullable=True),
    sa.Column('id_admin', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['usuarios.id_usuario'], name='FKe9cidxdcgyvjaxfgvi0sd33ic'),
    sa.PrimaryKeyConstraint('id_producto_descuento_admin'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente_contactos',
    sa.Column('id_cliente_contacto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('celular', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], name='FKe5lqjk1147ylwgi4e8vrjx3np'),
    sa.PrimaryKeyConstraint('id_cliente_contacto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_contacto_nombre', 'cliente_contactos', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('value_dolar',
    sa.Column('id_dolar', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta', mysql.FLOAT(), nullable=True),
    sa.Column('compra', mysql.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id_dolar'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('marcas',
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_marca'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_marca_nombre', 'marcas', ['nombre'], unique=False)
    op.create_index('ft_nombre_marca', 'marcas', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('cotizacion',
    sa.Column('id_cotizacion', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('activo', mysql.BIT(length=1), nullable=True),
    sa.Column('fecha_actualizacion', sa.DATE(), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.Column('igv', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('precio_venta', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('flete', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_cliente_contacto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referencia', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente_contacto'], ['cliente_contactos.id_cliente_contacto'], name='FKoxj4796ykt9vmlxttihns933u'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKe5mm4lduk05j9vrcoxhtdwh6y'),
    sa.PrimaryKeyConstraint('id_cotizacion'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_documento',
    sa.Column('id_producto_documentos', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ficha_tbt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ficha_tecnica', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url_imagen_producto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('protocolo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('imagen_producto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modelo_marca', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('version', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_producto_documentos'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UKmhtygq3agjndm7huyr0fgjkgq', 'producto_documento', ['id_marca', 'modelo_marca'], unique=True)
    op.create_table('unidades',
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo', mysql.ENUM('LONGITUD', 'PESO'), nullable=True),
    sa.PrimaryKeyConstraint('id_unidad'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dimensiones',
    sa.Column('id_dimension', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alto', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('ancho', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('largo', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK9am0r8eys74iuy67f81b6bnf5'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FK5f658584vna750itqnoc6f5hk'),
    sa.PrimaryKeyConstraint('id_dimension'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('compras_linea_credito',
    sa.Column('id_compras_linia_credito', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion_compra', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_compra', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fecha_vencimento', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('monto_compra', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('id_proveedor_credito', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor_credito'], ['proveedor_credito.id_proveedor_credito'], name='FK9dd08pip7djc9g0nrt6t0kp26'),
    sa.PrimaryKeyConstraint('id_compras_linia_credito'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('elemento_especifico',
    sa.Column('id_elemespec', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('id_subcat', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_subcat'], ['subcategoria.id_subcat'], name='fk_elemespec_subcat'),
    sa.PrimaryKeyConstraint('id_elemespec'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre', 'elemento_especifico', ['nombre'], unique=True)
    op.create_table('unidad_medida',
    sa.Column('id_unidad_medida', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_unidad_medida'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nombre_alternativo',
    sa.Column('id_nombre_alternativo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK9my8heosaj6koflkg183j25tt'),
    sa.PrimaryKeyConstraint('id_nombre_alternativo'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_nombre_alt', 'nombre_alternativo', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('documento',
    sa.Column('id_documento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('documento1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento5', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_producto_documento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto_documento'], ['producto_documento.id_producto_documentos'], name='FK4fuiixxmw82c7gagib1sa0cu9'),
    sa.PrimaryKeyConstraint('id_documento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_categoria',
    sa.Column('id_log_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_acción', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], name='FK11w3xdukibwqp8wgotrkq8pua'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FK70dfic868u2705byw525qx8rk'),
    sa.PrimaryKeyConstraint('id_log_categoria'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cotizaciones_versiones',
    sa.Column('id_cotizacion_versiones', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('id_cotizacion', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ruta_s3', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('version_cotizacion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.ENUM('EN_DESCUENTO', 'FINALIZADA', 'INICIAL'), nullable=True),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizacion.id_cotizacion'], name='FKf00tvqoa2q1soaaep26m85s94'),
    sa.PrimaryKeyConstraint('id_cotizacion_versiones'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_estado', 'cotizaciones_versiones', ['estado'], unique=False)
    op.create_table('productos_temporales',
    sa.Column('cotizacion_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('pc_ventausd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_categoria', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=True),
    sa.Column('utilidad_proyectada', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_temporales.id'], name='FKn4vmndqj6e4q5gb5msvywbag3'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_alternativo',
    sa.Column('id_producto_descontinuado', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto_alternativo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto_alternativo'], ['productos.id_producto'], name='FKgciga1od5jlok7x68cv9r6c60'),
    sa.ForeignKeyConstraint(['id_producto_descontinuado'], ['productos.id_producto'], name='FKqxmaljv5o7gy401ajfvn7skig'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_contactos',
    sa.Column('id_proveedor_contacto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('celular', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('sexo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor_contacto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('subcategoria',
    sa.Column('id_subcat', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_porcentaje_utilidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], name='FK5n9f7pm966nyw6mue7994u3bl'),
    sa.ForeignKeyConstraint(['id_porcentaje_utilidad'], ['porcentaje_utilidad.id_porcentaje_utilidad'], name='FK3bgqtuuh56kkxmh8hg4swx3g8'),
    sa.PrimaryKeyConstraint('id_subcat'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre', 'subcategoria', ['nombre'], unique=True)
    op.create_table('cotizaciones_temporales',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_categoria', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condiciones_pago', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('distrito', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('fecha_actualizacion', sa.DATE(), nullable=True),
    sa.Column('fecha_registro', sa.DATE(), nullable=True),
    sa.Column('forma_entrega', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ruc', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tiempo_entrega', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_proveedor', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('web', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nombre_comercial', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nacional', mysql.ENUM('INTERNACIONAL', 'NACIONAL'), nullable=True),
    sa.Column('rubro', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ruc', 'proveedores', ['ruc'], unique=False)
    op.create_index('ft_index_razon_social', 'proveedores', ['razon_social'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('tipo_roles',
    sa.Column('id_roles', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.Column('rol', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_roles'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_rubro',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FKfflxsehn87axtbwl8gk3oyu9s'),
    sa.ForeignKeyConstraint(['id_rubro'], ['rubros.id_rubro'], name='FKsde2q79rq53euyxhhw6nmbs55'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_descuento',
    sa.Column('id_producto_descuento', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fecha_aplicacion', sa.DATE(), nullable=True),
    sa.Column('id_vendedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_descuento_vendedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_descuento_vendedor'], ['descuento_vendedor.id_descuento_vendedor'], name='FKlrixs4galay9xa9f5fwprss6t'),
    sa.ForeignKeyConstraint(['id_vendedor'], ['usuarios.id_usuario'], name='FK61ovtj9vk1e4o9dpo5mbni9v6'),
    sa.PrimaryKeyConstraint('id_producto_descuento'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_rubro',
    sa.Column('id_log_rubro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_rubro'], ['rubros.id_rubro'], name='FKn1hdykej992dl8wn0hbbxtttm'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKbamuelj6rqng06006lcvwd944'),
    sa.PrimaryKeyConstraint('id_log_rubro'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_detalle',
    sa.Column('id_proveedor_detalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('igv', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('moneda', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('precio_costo_unitario', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('precio_costo_venta', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK1ary2gfjc67ftgptnbm2wpcsq'),
    sa.PrimaryKeyConstraint('id_proveedor_detalle'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('intermedia_proveedor_contacto',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_proveedor_contacto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FKn1t17b9jgfum5xycgjrexkdhb'),
    sa.ForeignKeyConstraint(['id_proveedor_contacto'], ['proveedor_contactos.id_proveedor_contacto'], name='FKj14kjrsx2f6uln7b571cbp5qb'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cbancaria_proveedor',
    sa.Column('id_cbancaria_proveedor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_dolares', mysql.DECIMAL(precision=38, scale=0), nullable=True),
    sa.Column('c_soles', mysql.DECIMAL(precision=38, scale=0), nullable=True),
    sa.Column('entidad_bancaria', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FKeawi1memes3h16x9pqpf0qibl'),
    sa.PrimaryKeyConstraint('id_cbancaria_proveedor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_cliente',
    sa.Column('id_tipo_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_idx_nombre', 'tipo_cliente', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('proveedor_marca',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='FKrufsocgd4b5bi6se6tnvxh4g0'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FK44i28581hmu3csigsdja8pty6'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_credito',
    sa.Column('id_proveedor_credito', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=True),
    sa.Column('fecha_inicio', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fecha_vencimiento', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('linia_credito', mysql.FLOAT(), nullable=True),
    sa.Column('saldo_restante_credito', mysql.FLOAT(), nullable=True),
    sa.Column('tiempo_credito', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FK8hxwd3sbeiq35m5ci580y807g'),
    sa.PrimaryKeyConstraint('id_proveedor_credito'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pesos',
    sa.Column('id_peso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK1gcrhyaocnyg6lqsyfxwu3aun'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FKcf6031n7j0s052n61wavm5arf'),
    sa.PrimaryKeyConstraint('id_peso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('peso_carrete',
    sa.Column('id_peso_carrete', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso_carrete', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FKnppt6rad57qtn4qwnqln1ms1m'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FKtb7l5432xqm6erv4t75bus2gt'),
    sa.PrimaryKeyConstraint('id_peso_carrete'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recalculos_temporales',
    sa.Column('cotizacion_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('diferencia', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pc_totalusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('porcentaje_utilidad_proyectada', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('precio_utilidad', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pv_neto_totalusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pv_unitusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_temporales.id'], name='FKnni5k27l91g5t71722d1mpx36'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productos',
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('codigo_empresa', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modelo_marca', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_subcat', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_elemespec', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_unidad_medida', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion_corta', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('descripcion_larga', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('fecha_modificacion_precio', sa.DATE(), nullable=True),
    sa.Column('id_producto_documento', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descontinuado', mysql.BIT(length=1), nullable=False),
    sa.Column('nombre_vector', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], name='FK7l7nhbb819h24i9apao7byvv'),
    sa.ForeignKeyConstraint(['id_elemespec'], ['elemento_especifico.id_elemespec'], name='FKbq9s3jk784hk4gxg25qyo50h0'),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='FKc1mrc7r89nch4xtol227kdwce'),
    sa.ForeignKeyConstraint(['id_producto_documento'], ['producto_documento.id_producto_documentos'], name='FKa75t1u1fvavwu8k60c98exrtb'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FK146wfsn2op2nvbfuxae33xbim'),
    sa.ForeignKeyConstraint(['id_subcat'], ['subcategoria.id_subcat'], name='FKedb4qlfuwf77fe91w61vanno0'),
    sa.ForeignKeyConstraint(['id_unidad_medida'], ['unidad_medida.id_unidad_medida'], name='FKhf27ojfxdv31ual4n86mhk3xd'),
    sa.PrimaryKeyConstraint('id_producto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_productos_estado', 'productos', ['estado'], unique=False)
    op.create_index('ft_nombre', 'productos', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('ft_modelo_marca', 'productos', ['modelo_marca'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('UKq078bit28d0egfhb9h74ffg7w', 'productos', ['nombre', 'id_proveedor', 'id_marca', 'id_unidad_medida'], unique=True)
    op.create_table('cliente',
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agente_retencion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('direccion_fiscal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('distrito', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('etiqueta', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_ultimo_contacto', sa.DATE(), nullable=True),
    sa.Column('nacional', mysql.ENUM('INTERNACIONAL', 'NACIONAL'), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('origen_contacto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rubro', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ruc', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_actualizacion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['tipo_cliente.id_tipo_cliente'], name='FK46k6k25yfkq3bvr0qf6b8ub5h'),
    sa.PrimaryKeyConstraint('id_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ruc', 'cliente', ['ruc'], unique=True)
    op.create_index('ft_index_razon_social', 'cliente', ['razon_social'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('productos_cotizaciones',
    sa.Column('id_producto_cotizacion', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso_total', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('producto_solicitado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('diferencia', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('precio_costo_total_usd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('tiempo_entrega', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('id_cotizacion_versiones', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('utilidad_proyectado', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto_descuento', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('p_uni_usd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('p_v_neto_usd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('p_v_uni_usd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('utilidad_real', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('utilidad_uni_real', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('utilidad_uni_proyectado', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('id_producto_descuento_admin', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('p_lista_usd', mysql.DECIMAL(precision=38, scale=2), nullable=True, comment='Precio de venta cuando se haya genera la utilidad proyectada  '),
    sa.ForeignKeyConstraint(['id_cotizacion_versiones'], ['cotizaciones_versiones.id_cotizacion_versiones'], name='FKq66w0mi3qnxofkgj9yln34sjv'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK9gk1156cneyigmhvandfoitrt'),
    sa.ForeignKeyConstraint(['id_producto_descuento'], ['producto_descuento.id_producto_descuento'], name='FKllinc3xbkafxjkabackxwrml7'),
    sa.ForeignKeyConstraint(['id_producto_descuento_admin'], ['producto_descuento_admin.id_producto_descuento_admin'], name='FK189cpxf41ngfd8fumuuxc4wr0'),
    sa.PrimaryKeyConstraint('id_producto_cotizacion'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('porcentaje_utilidad',
    sa.Column('id_porcentaje_utilidad', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('max_precio', mysql.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('min_precio', mysql.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('porcentaje', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_porcentaje_utilidad'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rubros',
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('nombre_normalizado', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='chk_estado'),
    sa.PrimaryKeyConstraint('id_rubro'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UQ_nombre', 'rubros', ['nombre'], unique=True)
    op.create_index('UKmoasxl2wx1yjvhqptvti4yv12', 'rubros', ['nombre_normalizado'], unique=True)
    op.create_table('descuento_vendedor',
    sa.Column('id_descuento_vendedor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activo', mysql.BIT(length=1), nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id_descuento_vendedor'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_ordenes_compra_id_orden'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_cotizaciones_id_cotizacion'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
