"""verificacion de tablas

Revision ID: c7a625819e14
Revises: 
Create Date: 2025-06-26 17:59:58.700191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7a625819e14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('cotizacion', 'referencia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=250),
               existing_nullable=True)


    op.create_index(op.f('ix_cotizaciones_versiones_id_cotizacion_versiones'), 'cotizaciones_versiones', ['id_cotizacion_versiones'], unique=False)
    op.alter_column('descuento_vendedor', 'id_descuento_vendedor',
               existing_type=mysql.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('descuento_vendedor', 'activo',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               nullable=True)
    op.create_index(op.f('ix_descuento_vendedor_id_descuento_vendedor'), 'descuento_vendedor', ['id_descuento_vendedor'], unique=False)
    op.add_column('elemento_especifico', sa.Column('id_porcentaje_utilidad', sa.Integer(), nullable=True))
    op.alter_column('elemento_especifico', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('elemento_especifico', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    op.create_index(op.f('ix_elemento_especifico_id_elemespec'), 'elemento_especifico', ['id_elemespec'], unique=False)
    op.create_foreign_key(None, 'elemento_especifico', 'porcentaje_utilidad', ['id_porcentaje_utilidad'], ['id_porcentaje_utilidad'])
    op.alter_column('marcas', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('marcas', 'estado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    
    op.create_index(op.f('ix_marcas_id_marca'), 'marcas', ['id_marca'], unique=False)
    op.alter_column('ordenes_compra', 'id_cotizacion',
               existing_type=mysql.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ordenes_compra', 'id_usuario',
               existing_type=mysql.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ordenes_compra', 'fecha_creacion',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('ordenes_compra', 'fecha_modificacion',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_foreign_key(None, 'ordenes_compra', 'cotizacion', ['id_cotizacion'], ['id_cotizacion'])
    op.alter_column('porcentaje_utilidad', 'max_precio',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=True)
    op.alter_column('porcentaje_utilidad', 'min_precio',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=True)
    op.alter_column('porcentaje_utilidad', 'porcentaje',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
    op.create_index(op.f('ix_porcentaje_utilidad_id_porcentaje_utilidad'), 'porcentaje_utilidad', ['id_porcentaje_utilidad'], unique=False)
    op.create_index(op.f('ix_producto_descuento_id_producto_descuento'), 'producto_descuento', ['id_producto_descuento'], unique=False)
    op.create_index(op.f('ix_producto_descuento_admin_id_producto_descuento_admin'), 'producto_descuento_admin', ['id_producto_descuento_admin'], unique=False)
    op.alter_column('productos', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('productos', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('productos', 'descontinuado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('productos', 'id_marca',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('productos', 'id_proveedor',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_productos_id_producto'), 'productos', ['id_producto'], unique=False)
    op.alter_column('productos_cotizaciones', 'estado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('productos_cotizaciones', 'p_lista_usd',
               existing_type=mysql.DECIMAL(precision=38, scale=2),
               comment=None,
               existing_comment='Precio de venta cuando se haya genera la utilidad proyectada  ',
               existing_nullable=True)
    op.create_index(op.f('ix_productos_cotizaciones_id_producto_cotizacion'), 'productos_cotizaciones', ['id_producto_cotizacion'], unique=False)
    op.alter_column('proveedor_contactos', 'celular',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('proveedor_contactos', 'observacion',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'telefono',
               existing_type=mysql.INTEGER(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'cargo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('proveedor_contactos', 'nombre',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'estado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               nullable=True)
    op.create_index(op.f('ix_proveedor_contactos_id_proveedor_contacto'), 'proveedor_contactos', ['id_proveedor_contacto'], unique=False)
    op.drop_column('proveedor_contactos', 'sexo')
    op.add_column('proveedor_detalle', sa.Column('id_proveedor', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_proveedor_detalle_id_proveedor_detalle'), 'proveedor_detalle', ['id_proveedor_detalle'], unique=False)
    op.create_foreign_key(None, 'proveedor_detalle', 'proveedores', ['id_proveedor'], ['id_proveedor'])
    op.alter_column('proveedores', 'estado',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('proveedores', 'razon_social',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('proveedores', 'ruc',
               existing_type=mysql.BIGINT(),
               nullable=True)
    
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.add_column('subcategoria', sa.Column('id_elemespec', sa.Integer(), nullable=True))
    op.alter_column('subcategoria', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('subcategoria', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    
    op.create_index(op.f('ix_subcategoria_id_subcat'), 'subcategoria', ['id_subcat'], unique=False)
    op.create_foreign_key(None, 'subcategoria', 'elemento_especifico', ['id_elemespec'], ['id_elemespec'])
    op.create_index(op.f('ix_unidad_medida_id_unidad_medida'), 'unidad_medida', ['id_unidad_medida'], unique=False)
    op.alter_column('usuarios', 'celular',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('usuarios', 'fecha_modificacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'fecha_modificacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fecha_creacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('usuarios', 'celular',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_unidad_medida_id_unidad_medida'), table_name='unidad_medida')
    op.drop_constraint(None, 'subcategoria', type_='foreignkey')
    op.drop_index(op.f('ix_subcategoria_id_subcat'), table_name='subcategoria')
    op.create_index('nombre', 'subcategoria', ['nombre'], unique=True)
    op.alter_column('subcategoria', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('subcategoria', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('subcategoria', 'id_elemespec')
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.create_index('idx_ruc', 'proveedores', ['ruc'], unique=False)
    op.create_index('ft_index_razon_social', 'proveedores', ['razon_social'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('proveedores', 'ruc',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('proveedores', 'razon_social',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('proveedores', 'estado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               nullable=False)
    op.drop_constraint(None, 'proveedor_detalle', type_='foreignkey')
    op.drop_index(op.f('ix_proveedor_detalle_id_proveedor_detalle'), table_name='proveedor_detalle')
    op.drop_column('proveedor_detalle', 'id_proveedor')
    op.add_column('proveedor_contactos', sa.Column('sexo', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_proveedor_contactos_id_proveedor_contacto'), table_name='proveedor_contactos')
    op.alter_column('proveedor_contactos', 'estado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               nullable=False)
    op.alter_column('proveedor_contactos', 'nombre',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'cargo',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('proveedor_contactos', 'telefono',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'observacion',
               existing_type=sa.VARCHAR(length=250),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('proveedor_contactos', 'celular',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_productos_cotizaciones_id_producto_cotizacion'), table_name='productos_cotizaciones')
    op.alter_column('productos_cotizaciones', 'p_lista_usd',
               existing_type=mysql.DECIMAL(precision=38, scale=2),
               comment='Precio de venta cuando se haya genera la utilidad proyectada  ',
               existing_nullable=True)
    op.alter_column('productos_cotizaciones', 'estado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               nullable=False)
    op.create_foreign_key('FKa75t1u1fvavwu8k60c98exrtb', 'productos', 'producto_documento', ['id_producto_documento'], ['id_producto_documentos'])
    op.drop_index(op.f('ix_productos_id_producto'), table_name='productos')
    op.create_index('idx_productos_estado', 'productos', ['estado'], unique=False)
    op.create_index('ft_nombre', 'productos', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('ft_modelo_marca', 'productos', ['modelo_marca'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('UKq078bit28d0egfhb9h74ffg7w', 'productos', ['nombre', 'id_proveedor', 'id_marca', 'id_unidad_medida'], unique=True)
    op.alter_column('productos', 'id_proveedor',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('productos', 'id_marca',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('productos', 'descontinuado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               nullable=False)
    op.alter_column('productos', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('productos', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_producto_descuento_admin_id_producto_descuento_admin'), table_name='producto_descuento_admin')
    op.drop_index(op.f('ix_producto_descuento_id_producto_descuento'), table_name='producto_descuento')
    op.drop_index(op.f('ix_porcentaje_utilidad_id_porcentaje_utilidad'), table_name='porcentaje_utilidad')
    op.alter_column('porcentaje_utilidad', 'porcentaje',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
    op.alter_column('porcentaje_utilidad', 'min_precio',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=False)
    op.alter_column('porcentaje_utilidad', 'max_precio',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=False)
    op.drop_constraint(None, 'ordenes_compra', type_='foreignkey')
    op.alter_column('ordenes_compra', 'fecha_modificacion',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('ordenes_compra', 'fecha_creacion',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=False)
    op.alter_column('ordenes_compra', 'id_usuario',
               existing_type=sa.BIGINT(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('ordenes_compra', 'id_cotizacion',
               existing_type=sa.BIGINT(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_marcas_id_marca'), table_name='marcas')
    op.create_index('idx_marca_nombre', 'marcas', ['nombre'], unique=False)
    op.create_index('ft_nombre_marca', 'marcas', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('marcas', 'estado',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('marcas', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'elemento_especifico', type_='foreignkey')
    op.drop_index(op.f('ix_elemento_especifico_id_elemespec'), table_name='elemento_especifico')
    op.create_index('nombre', 'elemento_especifico', ['nombre'], unique=True)
    op.alter_column('elemento_especifico', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('elemento_especifico', 'nombre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('elemento_especifico', 'id_porcentaje_utilidad')
    op.drop_index(op.f('ix_descuento_vendedor_id_descuento_vendedor'), table_name='descuento_vendedor')
    op.alter_column('descuento_vendedor', 'activo',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               nullable=False)
    op.alter_column('descuento_vendedor', 'id_descuento_vendedor',
               existing_type=sa.BIGINT(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_cotizaciones_versiones_id_cotizacion_versiones'), table_name='cotizaciones_versiones')
    op.create_index('idx_estado', 'cotizaciones_versiones', ['estado'], unique=False)
    op.add_column('cotizacion', sa.Column('id_cliente_contacto', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FKoxj4796ykt9vmlxttihns933u', 'cotizacion', 'cliente_contactos', ['id_cliente_contacto'], ['id_cliente_contacto'])
    op.alter_column('cotizacion', 'referencia',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.create_index('idx_categoria_nombre', 'categoria', ['nombre'], unique=False)
    op.create_index('ft_nombre_categoria', 'categoria', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('UK35t4wyxqrevf09uwx9e9p6o75', 'categoria', ['nombre'], unique=True)
    op.create_table('proveedor_marca',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='FKrufsocgd4b5bi6se6tnvxh4g0'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FK44i28581hmu3csigsdja8pty6'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_cliente',
    sa.Column('id_tipo_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_idx_nombre', 'tipo_cliente', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('cliente_contactos',
    sa.Column('id_cliente_contacto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('celular', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], name='FKe5lqjk1147ylwgi4e8vrjx3np'),
    sa.PrimaryKeyConstraint('id_cliente_contacto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_contacto_nombre', 'cliente_contactos', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('cotizaciones_temporales',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_categoria', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agente_retencion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departamento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('direccion_fiscal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('distrito', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.Column('etiqueta', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_ultimo_contacto', sa.DATE(), nullable=True),
    sa.Column('nacional', mysql.ENUM('INTERNACIONAL', 'NACIONAL'), nullable=True),
    sa.Column('observaciones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('origen_contacto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provincia', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rubro', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ruc', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_actualizacion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['tipo_cliente.id_tipo_cliente'], name='FK46k6k25yfkq3bvr0qf6b8ub5h'),
    sa.PrimaryKeyConstraint('id_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ruc', 'cliente', ['ruc'], unique=True)
    op.create_index('ft_index_razon_social', 'cliente', ['razon_social'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('proveedor_credito',
    sa.Column('id_proveedor_credito', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=True),
    sa.Column('fecha_inicio', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fecha_vencimiento', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('linia_credito', mysql.FLOAT(), nullable=True),
    sa.Column('saldo_restante_credito', mysql.FLOAT(), nullable=True),
    sa.Column('tiempo_credito', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FK8hxwd3sbeiq35m5ci580y807g'),
    sa.PrimaryKeyConstraint('id_proveedor_credito'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recalculos_temporales',
    sa.Column('cotizacion_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('diferencia', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pc_totalusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('porcentaje_utilidad_proyectada', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('precio_utilidad', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pv_neto_totalusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('pv_unitusd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_temporales.id'], name='FKnni5k27l91g5t71722d1mpx36'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('unidades',
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo', mysql.ENUM('LONGITUD', 'PESO'), nullable=True),
    sa.PrimaryKeyConstraint('id_unidad'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_alternativo',
    sa.Column('id_producto_descontinuado', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto_alternativo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto_alternativo'], ['productos.id_producto'], name='FKgciga1od5jlok7x68cv9r6c60'),
    sa.ForeignKeyConstraint(['id_producto_descontinuado'], ['productos.id_producto'], name='FKqxmaljv5o7gy401ajfvn7skig'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_categoria',
    sa.Column('id_log_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_acción', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], name='FK11w3xdukibwqp8wgotrkq8pua'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FK70dfic868u2705byw525qx8rk'),
    sa.PrimaryKeyConstraint('id_log_categoria'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario_roles',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['tipo_roles.id_roles'], name='FKme6m3sw9vo6513q4f7b5jkcog'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKor5vdfg7bv12b37vaawa9lee2'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedor_rubro',
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FKfflxsehn87axtbwl8gk3oyu9s'),
    sa.ForeignKeyConstraint(['id_rubro'], ['rubros.id_rubro'], name='FKsde2q79rq53euyxhhw6nmbs55'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_roles',
    sa.Column('id_roles', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.Column('rol', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id_roles'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productos_temporales',
    sa.Column('cotizacion_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('pc_ventausd', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_categoria', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=True),
    sa.Column('utilidad_proyectada', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_temporales.id'], name='FKn4vmndqj6e4q5gb5msvywbag3'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('utilidad_venta',
    sa.Column('id_utilidad_venta', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_utilidad_venta'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cbancaria_proveedor',
    sa.Column('id_cbancaria_proveedor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('c_dolares', mysql.DECIMAL(precision=38, scale=0), nullable=True),
    sa.Column('c_soles', mysql.DECIMAL(precision=38, scale=0), nullable=True),
    sa.Column('entidad_bancaria', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], name='FKeawi1memes3h16x9pqpf0qibl'),
    sa.PrimaryKeyConstraint('id_cbancaria_proveedor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('compras_linea_credito',
    sa.Column('id_compras_linia_credito', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion_compra', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_compra', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fecha_vencimento', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('monto_compra', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('id_proveedor_credito', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.BIT(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor_credito'], ['proveedor_credito.id_proveedor_credito'], name='FK9dd08pip7djc9g0nrt6t0kp26'),
    sa.PrimaryKeyConstraint('id_compras_linia_credito'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('value_dolar',
    sa.Column('id_dolar', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venta', mysql.FLOAT(), nullable=True),
    sa.Column('compra', mysql.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id_dolar'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_rubro',
    sa.Column('id_log_rubro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_rubro'], ['rubros.id_rubro'], name='FKn1hdykej992dl8wn0hbbxtttm'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKbamuelj6rqng06006lcvwd944'),
    sa.PrimaryKeyConstraint('id_log_rubro'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_documento',
    sa.Column('id_producto_documentos', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ficha_tbt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ficha_tecnica', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url_imagen_producto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('protocolo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('imagen_producto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modelo_marca', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('version', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_producto_documentos'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UKmhtygq3agjndm7huyr0fgjkgq', 'producto_documento', ['id_marca', 'modelo_marca'], unique=True)
    op.create_table('log_marca',
    sa.Column('id_log_marca', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detalles', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_accion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tipo_acción', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id_marca'], name='FKgrrnwmwn7xxx0kpcb78k4lqtf'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='FKhwuar6w4p641qrxl1j69n34hc'),
    sa.PrimaryKeyConstraint('id_log_marca'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('peso_carrete',
    sa.Column('id_peso_carrete', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso_carrete', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FKnppt6rad57qtn4qwnqln1ms1m'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FKtb7l5432xqm6erv4t75bus2gt'),
    sa.PrimaryKeyConstraint('id_peso_carrete'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pesos',
    sa.Column('id_peso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK1gcrhyaocnyg6lqsyfxwu3aun'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FKcf6031n7j0s052n61wavm5arf'),
    sa.PrimaryKeyConstraint('id_peso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rubros',
    sa.Column('id_rubro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('observacion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_modificacion', sa.DATE(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('nombre_normalizado', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`estado` in (0,1))', name='chk_estado'),
    sa.PrimaryKeyConstraint('id_rubro'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UQ_nombre', 'rubros', ['nombre'], unique=True)
    op.create_index('UKmoasxl2wx1yjvhqptvti4yv12', 'rubros', ['nombre_normalizado'], unique=True)
    op.create_table('documento',
    sa.Column('id_documento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('documento1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documento5', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_producto_documento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto_documento'], ['producto_documento.id_producto_documentos'], name='FK4fuiixxmw82c7gagib1sa0cu9'),
    sa.PrimaryKeyConstraint('id_documento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nombre_alternativo',
    sa.Column('id_nombre_alternativo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK9my8heosaj6koflkg183j25tt'),
    sa.PrimaryKeyConstraint('id_nombre_alternativo'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ft_nombre_alt', 'nombre_alternativo', ['nombre'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('dimensiones',
    sa.Column('id_dimension', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alto', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('ancho', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('largo', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('id_producto', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_unidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='FK9am0r8eys74iuy67f81b6bnf5'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades.id_unidad'], name='FK5f658584vna750itqnoc6f5hk'),
    sa.PrimaryKeyConstraint('id_dimension'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
